# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name' : 'HR Expense Advance | HR Advance Expense | Mass Advance Expense',
    'author': 'OMAX Informatics',
    'version': '1.0',
    'website': 'https://www.omaxinformatics.com',
    'category': 'Human Resources,Accounting',
    'description' : '''
        This App allows employees to create advance expenses requests
    ''',
    'depends' : ['account', 'hr_expense','hr', 'sign'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/advance_expense_cron.xml',
        'data/mail_template_data.xml',
        'wizard/adv_exp_reject_view.xml',
        'views/hr_employee.xml',
        'views/advance_expense.xml',
        'wizard/mass_advance_expense.xml',
        'views/account_move.xml',
        'views/hr_expense.xml',
        'views/res_config_settings.xml',
        'wizard/adv_exp_report_view.xml',
        'report/advance_expense_voucher_report.xml',
        'report/report_menu.xml',
    ],
    'demo': [],
    'test': [],
    'images': ['static/description/banner.png',],
    'license': 'OPL-1',
    'currency':'EUR',
    'price': 130.0,
    'installable' : True,
    'auto_install' : False,
    'application' : True,
    'pre_init_hook': 'pre_init_check',
    'live_test_url': 'https://youtu.be/nX-8l3nWSBg',
    'module_type': 'official',
    'summary': '''
        This App allows employees to create advance expenses requests  Approval Reject functionality available in advance expense request  Advance expense submit, approve and reject then auto send mail to configure user or employee  Once approved and then paid advance expense that time auto create advance expense Journal entry and after that user can submit advance expense then auto create default odoo expense  Configure users can create multiple advance expenses from 'Mass Advance Expense' wizard  Expense of advance expense is not paid then add restriction to create new advance expense and this restriction not apply in 'Mass Advance Expense' wizard  Configure users have access to bypass restriction of creating new advance expense for specific employee  User can download Advance expense pdf report from Advance expense form tree view  User can download excel report of Advance Expense from 'Advance Expense Report' wizard and multiple filter options available in wizard  Auto send Reminder for retirement mail to employee and approval based on configuration Employee create advance expense request Approver can Approve or Reject Once employee has been paid for advance expense then Journal entry created Employee can submit actual expense agaist the advance expense Employee will not be able to submit another advance expense if any pending advance expense is not retired Configuration available to bypass above restriction for specific employee Expense Admin can allocate mass advance expense entries for multiple employees Download pdf report of Advance Expense from tree/form view Download excel report of Advance Expense from 'Advance Expense Report' wizard Multiple filter options available in 'Advance Expense Report' wizard Auto send Reminder for retirement mail to employee and approval based on configuration

Cette application permet aux employés de créer des demandes de dépenses anticipées. Fonctionnalité de rejet d'approbation disponible dans la demande de dépenses anticipée. Soumettre, approuver et rejeter les dépenses anticipées, puis envoyer automatiquement un courrier pour configurer l'utilisateur ou l'employé. cet utilisateur peut soumettre des dépenses anticipées, puis créer automatiquement une dépense odoo par défaut. Configurer les utilisateurs peuvent créer plusieurs dépenses anticipées à partir de l'assistant « Dépenses anticipées en masse ». Les dépenses anticipées ne sont pas payées, puis ajouter une restriction pour créer de nouvelles dépenses anticipées et cette restriction ne s'applique pas dans « Avance massive ». Assistant de dépenses Configurer les utilisateurs pour contourner la restriction de création de nouvelles dépenses anticipées pour un employé spécifique. L'utilisateur peut télécharger le rapport PDF des dépenses anticipées à partir de l'arborescence du formulaire de dépenses anticipées. L'utilisateur peut télécharger le rapport Excel des dépenses anticipées à partir de l'assistant « Rapport de dépenses anticipées » et de plusieurs options de filtrage. disponible dans l'assistant Envoi automatique d'un courrier de rappel pour la retraite à l'employé et approbation en fonction de la configuration L'employé crée une demande de dépenses anticipées L'approbateur peut approuver ou rejeter Une fois que l'employé a été payé pour les dépenses anticipées, l'entrée de journal est créée L'employé peut soumettre les dépenses réelles par rapport à la dépense anticipée L'employé ne le fera pas être en mesure de soumettre une autre dépense anticipée si une dépense anticipée en attente n'est pas retirée Configuration disponible pour contourner la restriction ci-dessus pour un employé spécifique L'administrateur des dépenses peut allouer des entrées de dépenses anticipées en masse pour plusieurs employés Télécharger le rapport PDF des dépenses anticipées à partir de la vue arborescence/formulaire Télécharger le rapport Excel de Avancez les dépenses à partir de l'assistant « Rapport de dépenses anticipé » Plusieurs options de filtrage disponibles dans l'assistant « Rapport de dépenses anticipé » Envoi automatique d'un rappel de courrier de retraite à l'employé et approbation en fonction de la configuration

Questa app consente ai dipendenti di creare richieste di spesa anticipata Funzionalità di rifiuto di approvazione disponibile nella richiesta di spesa anticipata Invia, approva e rifiuta la spesa anticipata, quindi invia automaticamente la posta per configurare l'utente o il dipendente Una volta approvata e pagata la spesa anticipata in quel momento, crea automaticamente la voce nel diario delle spese anticipate e dopo quell'utente può inviare spese anticipate e quindi creare automaticamente spese odoo predefinite Configurare gli utenti possono creare più spese anticipate dalla procedura guidata 'Spese anticipate di massa' Le spese anticipate non vengono pagate, quindi aggiungere una restrizione per creare nuove spese anticipate e questa restrizione non si applica in 'Anticipo di massa' Procedura guidata Spese Configura gli utenti hanno accesso per aggirare la restrizione di creazione di nuove spese anticipate per un dipendente specifico L'utente può scaricare il report pdf delle spese anticipate dalla visualizzazione ad albero del modulo spese anticipate L'utente può scaricare il report Excel delle spese anticipate dalla procedura guidata 'Report spese anticipate' e molteplici opzioni di filtro disponibile nella procedura guidata Invio automatico e-mail di promemoria per la pensione al dipendente e approvazione in base alla configurazione Il dipendente crea una richiesta di spesa anticipata L'approvatore può approvare o rifiutare Una volta che il dipendente è stato pagato per la spesa anticipata, viene creata la voce di giornale Il dipendente può inviare la spesa effettiva a fronte della spesa anticipata Il dipendente non lo farà essere in grado di inviare un'altra spesa anticipata se una spesa anticipata in sospeso non è stata ritirata Configurazione disponibile per aggirare la restrizione di cui sopra per dipendenti specifici L'amministratore delle spese può allocare voci di spesa anticipata di massa per più dipendenti Scarica il report pdf delle spese anticipate dalla visualizzazione ad albero/modulo Scarica il report Excel di Spese anticipate dalla procedura guidata 'Relazione spese anticipata' Molteplici opzioni di filtro disponibili nella procedura guidata 'Relazione spese anticipata' Invio automatico del promemoria per la pensione al dipendente e dell'approvazione in base alla configurazione

Esta aplicación permite a los empleados crear solicitudes de gastos por adelantado. Funcionalidad de aprobación y rechazo disponible en la solicitud de gastos por adelantado. Enviar, aprobar y rechazar gastos por adelantado y luego enviar automáticamente un correo para configurar al usuario o empleado. Una vez aprobado y luego pagado el gasto por adelantado, ese momento crea automáticamente el asiento de diario de gastos por adelantado y después. ese usuario puede enviar gastos por adelantado y luego crear automáticamente el gasto predeterminado de odoo. Configurar que los usuarios pueden crear múltiples gastos por adelantado desde el asistente 'Gastos por adelantado en masa'. El gasto del gasto por adelantado no se paga, luego agregue una restricción para crear un nuevo gasto por adelantado y esta restricción no se aplica en 'Adelanto en masa' Asistente de gastos Configurar que los usuarios tengan acceso para evitar la restricción de crear nuevos gastos anticipados para un empleado específico. El usuario puede descargar el informe de gastos anticipados en PDF desde la vista de árbol del formulario de gastos anticipados. El usuario puede descargar el informe Excel de gastos anticipados desde el asistente 'Informe de gastos anticipados' y múltiples opciones de filtro. disponible en el asistente Envío automático de recordatorio para el correo de jubilación al empleado y aprobación basada en la configuración El empleado crea una solicitud de gastos anticipados El aprobador puede aprobar o rechazar Una vez que al empleado se le ha pagado el gasto anticipado, se crea un asiento en el diario El empleado puede enviar el gasto real contra el gasto anticipado El empleado no lo hará poder enviar otro gasto anticipado si algún gasto anticipado pendiente no se retira Configuración disponible para evitar la restricción anterior para empleados específicos El administrador de gastos puede asignar entradas masivas de gastos anticipados para varios empleados Descargar el informe en PDF de Gastos anticipados desde la vista de árbol/formulario Descargar el informe de Excel de Gastos anticipados desde el asistente 'Informe de gastos anticipados' Múltiples opciones de filtro disponibles en el asistente 'Informe de gastos anticipados' Envío automático de recordatorio de correo de jubilación al empleado y aprobación según la configuración

Mit dieser App können Mitarbeiter Vorabkostenanträge erstellen. Die Funktion „Genehmigen und Ablehnen“ ist in Vorabkostenanträgen verfügbar. Vorabkosten einreichen, genehmigen und ablehnen und dann automatisch eine E-Mail an die Konfiguration von Benutzer oder Mitarbeiter senden. Nach der Genehmigung und anschließenden Zahlung von Vorschusskosten wird zu diesem Zeitpunkt automatisch ein Vorschusskostenjournaleintrag erstellt und danach Dieser Benutzer kann Vorabausgaben einreichen und dann automatisch standardmäßige Odoo-Ausgaben erstellen. Benutzer können konfigurieren, dass sie mit dem Assistenten „Massenvorschuss“ mehrere Vorabausgaben erstellen können. Vorabkosten werden nicht bezahlt. Fügen Sie dann eine Einschränkung zum Erstellen neuer Vorabkosten hinzu. Diese Einschränkung gilt nicht für „Massenvorschuss“. Assistent „Ausgaben“ konfigurieren. Benutzer haben Zugriff auf die Umgehung der Einschränkung, neue Vorabausgaben für einen bestimmten Mitarbeiter zu erstellen. Benutzer können den PDF-Bericht über Vorabausgaben in der Strukturansicht des Formulars „Vorabausgaben“ herunterladen. Benutzer können einen Excel-Bericht über Vorabausgaben über den Assistenten „Vorabausgabenabrechnung“ und mehrere Filteroptionen herunterladen Im Assistenten verfügbar. Automatisches Senden einer E-Mail zur Ruhestandserinnerung an den Mitarbeiter und Genehmigung basierend auf der Konfiguration. Mitarbeiter erstellt Kostenvorschussantrag. Der Genehmiger kann genehmigen oder ablehnen. Sobald der Mitarbeiter für Vorschusskosten bezahlt wurde, wird ein Journaleintrag erstellt. Der Mitarbeiter kann tatsächliche Ausgaben gegenüber den Vorschusskosten einreichen. Der Mitarbeiter kann dies nicht tun in der Lage sein, eine weitere Vorschussausgabe einzureichen, wenn eine ausstehende Vorschussausgabe nicht zurückgezogen wird. Konfiguration zur Umgehung der oben genannten Einschränkung für bestimmte Mitarbeiter verfügbar. Der Ausgabenadministrator kann Massenvorschusseinträge für mehrere Mitarbeiter zuweisen. PDF-Bericht über Vorschussausgaben aus der Baum-/Formularansicht herunterladen. Excel-Bericht von herunterladen Vorabausgaben über den Assistenten „Vorababrechnungen“ Mehrere Filteroptionen im Assistenten für „Vorababrechnungen“ verfügbar. Automatisches Senden einer E-Mail zur Erinnerung an den Ruhestand an den Mitarbeiter und Genehmigung basierend auf der Konfiguration

يسمح هذا التطبيق للموظفين بإنشاء طلبات النفقات المسبقة، وظيفة رفض الموافقة المتوفرة في طلب النفقات المسبقة، إرسال النفقات المسبقة والموافقة والرفض ثم إرسال البريد تلقائيًا لتكوين المستخدم أو الموظف بمجرد الموافقة ثم دفع النفقات المسبقة في ذلك الوقت، إنشاء تلقائي للنفقات المسبقة، إدخال دفتر اليومية وبعد ذلك يمكن لهذا المستخدم إرسال النفقات المقدمة ثم إنشاء نفقات odoo الافتراضية تلقائيًا. يمكن تكوين المستخدمين من إنشاء نفقات مسبقة متعددة من معالج 'النفقات المسبقة الجماعية' لم يتم دفع نفقات النفقات المقدمة ثم قم بإضافة قيد لإنشاء نفقات مسبقة جديدة ولا ينطبق هذا القيد في 'الدفعة الجماعية' معالج 'المصروفات' تكوين المستخدمين لديهم حق الوصول إلى تجاوز القيود المفروضة على إنشاء نفقات مسبقة جديدة لموظف معين. يمكن للمستخدم تنزيل تقرير النفقات المسبقة بتنسيق pdf من العرض الشجري لنموذج النفقات المسبقة. يمكن للمستخدم تنزيل تقرير Excel للنفقات المسبقة من معالج 'تقرير النفقات المسبقة' وخيارات تصفية متعددة متوفر في المعالج، إرسال تلقائي للتذكير ببريد التقاعد إلى الموظف والموافقة بناءً على التكوين، يقوم الموظف بإنشاء طلب نفقات مسبقة يمكن للموافق الموافقة أو الرفض بمجرد دفع الموظف للنفقات المقدمة، ثم يتم إنشاء قيد دفتر اليومية يمكن للموظف تقديم النفقات الفعلية مقابل النفقات المقدمة لن يقوم الموظف بذلك تكون قادرًا على إرسال نفقات مسبقة أخرى إذا لم يتم إيقاف أي نفقات مسبقة معلقة التكوين متاح لتجاوز القيود المذكورة أعلاه لموظف محدد يمكن لمدير النفقات تخصيص إدخالات النفقات المسبقة الجماعية لعدة موظفين تنزيل تقرير pdf للنفقات المقدمة من عرض الشجرة/النموذج تنزيل تقرير Excel الخاص النفقات المسبقة من معالج 'تقرير النفقات المسبقة' تتوفر خيارات تصفية متعددة في معالج 'تقرير النفقات المسبقة' إرسال تلقائي للتذكير ببريد التقاعد إلى الموظف والموافقة بناءً على التكوين
        
	''',
}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
